Update test1.yml

diff --git a/.github/workflows/test1.yml b/.github/workflows/test1.yml
--- a/.github/workflows/test1.yml
+++ b/.github/workflows/test1.yml
@@ -15,16 +15,18 @@ jobs:
         
       - name: install dependancies
         run: |
-          pip install flask requests pytest 
+          pip install flask requests pytest
+          pytest "unit_test.py"
       
-      - name: unit test report
-        run: |
-         if pytest -q unit_Test.py; then
-             echo " unit test sucess";
-         else
-             echo "unit test faild"
-             exit 1
-         fi
+      
+      # - name: unit test report
+      #   run: |
+      #    if pytest -q unit_Test.py; then
+      #        echo " unit test sucess";
+      #    else
+      #        echo "unit test faild"
+      #        exit 1
+      #    fi
          
             
           
