Update test1.yml

diff --git a/.github/workflows/test1.yml b/.github/workflows/test1.yml
--- a/.github/workflows/test1.yml
+++ b/.github/workflows/test1.yml
@@ -22,7 +22,9 @@ jobs:
          if [ $? -eq 0 ]; then
              echo "sucess";
          else
-             echo "faild"
+             echo "faild";
+             exit 1
+         fi
             
           
   
