Update test1.yml

diff --git a/.github/workflows/test1.yml b/.github/workflows/test1.yml
--- a/.github/workflows/test1.yml
+++ b/.github/workflows/test1.yml
@@ -19,14 +19,14 @@ jobs:
           pytest "unit_test.py"
       
       
-      # - name: unit test report
-      #   run: |
-      #    if pytest -q unit_Test.py; then
-      #        echo " unit test sucess";
-      #    else
-      #        echo "unit test faild"
-      #        exit 1
-      #    fi
+      - name: unit test report
+        run: |
+         if pytest -q unit_Test.py; then
+             echo " unit test sucess";
+         else
+             echo "unit test faild"
+             exit 1
+         fi
          
             
           
